###############################################################################
# Makefile for the project MR
###############################################################################

## General Flags
PROJECT = MR
MCU = atmega128
TARGET = MR.elf
CC = avr-gcc

CPP = avr-g++

## Options common to compile, link and assembly rules
COMMON = -mmcu=$(MCU)

## Compile options common for all C compilation units.
CFLAGS = $(COMMON)
CFLAGS += -Wall -gdwarf-2 -std=gnu99   -DF_CPU=14745600UL -Os -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums
CFLAGS += -MD -MP -MT $(*F).o -MF dep/$(@F).d 

## Assembly specific flags
ASMFLAGS = $(COMMON)
ASMFLAGS += $(CFLAGS)
ASMFLAGS += -x assembler-with-cpp -Wa,-gdwarf2

## Linker flags
LDFLAGS = $(COMMON)
LDFLAGS +=  -Wl,-Map=MR.map


## Intel Hex file production flags
HEX_FLASH_FLAGS = -R .eeprom -R .fuse -R .lock -R .signature

HEX_EEPROM_FLAGS = -j .eeprom
HEX_EEPROM_FLAGS += --set-section-flags=.eeprom="alloc,load"
HEX_EEPROM_FLAGS += --change-section-lma .eeprom=0 --no-change-warnings


## Libraries
LIBS = -lc 

## Objects that must be built in order to link
OBJECTS = Interface.o MobileRobot.o Motor.o Move.o Sensor.o 

## Objects explicitly added by the user
LINKONLYOBJECTS = 

## Build
all: $(TARGET) MR.hex MR.eep MR.lss size

## Compile
Interface.o: ../Interface.c
	$(CC) $(INCLUDES) $(CFLAGS) -c  $<

MobileRobot.o: ../MobileRobot.c
	$(CC) $(INCLUDES) $(CFLAGS) -c  $<

Motor.o: ../Motor.c
	$(CC) $(INCLUDES) $(CFLAGS) -c  $<

Move.o: ../Move.c
	$(CC) $(INCLUDES) $(CFLAGS) -c  $<

Sensor.o: ../Sensor.c
	$(CC) $(INCLUDES) $(CFLAGS) -c  $<

##Link
$(TARGET): $(OBJECTS)
	 $(CC) $(LDFLAGS) $(OBJECTS) $(LINKONLYOBJECTS) $(LIBDIRS) $(LIBS) -o $(TARGET)

%.hex: $(TARGET)
	avr-objcopy -O ihex $(HEX_FLASH_FLAGS)  $< $@

%.eep: $(TARGET)
	-avr-objcopy $(HEX_EEPROM_FLAGS) -O ihex $< $@ || exit 0

%.lss: $(TARGET)
	avr-objdump -h -S $< > $@

size: ${TARGET}
	@echo
	@avr-size -C --mcu=${MCU} ${TARGET}

## Clean target
.PHONY: clean
clean:
	-rm -rf $(OBJECTS) MR.elf dep/* MR.hex MR.eep MR.lss MR.map


## Other dependencies
-include $(shell mkdir dep 2>NUL) $(wildcard dep/*)

